import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { Space_Grotesk } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { CartProvider } from "@/components/CartContext";
import { BackgroundFX } from "@/components/BackgroundFX";
import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-grotesk",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${spaceGrotesk.variable} ${geistMono.variable} antialiased bg-black text-white`}> 
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <CartProvider>
            <BackgroundFX />
            <Navbar />
            <div className="pt-16 min-h-[calc(100vh-64px)]">
              {children}
            </div>
            <Footer />
          </CartProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
